version: '3.8'

volumes:
  mariadb_data:
    driver: local

services:
  mariadb:
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: kate_db
      MYSQL_USER: kate_user
      MYSQL_PASSWORD: kate_password
    ports:
      - "23306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9082:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb:3306



